### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by darksidelemm** [wb9coy/RS41cam#2]
As per https://github.com/mikaelnousiainen/RS41ng/issues/50, to be able to integrate some of this code into other projects (e.g. the RS41ng repository), there needs to be some license included in your repository.

If you're happy with the GPL v2 license, then just including the https://raw.githubusercontent.com/mikaelnousiainen/RS41ng/main/LICENSE.md file in your repository would be sufficient.

**Comment by wb9coy** [comment]
Hi Mark does this statement go in both the .h and .c files ?
________________________________
From: Mark Jessop ***@***.***>
Sent: Thursday, September 7, 2023 3:22 AM
To: wb9coy/RS41cam ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wb9coy/RS41cam] Open Source License? (Issue #2)


As per mikaelnousiainen/RS41ng#50<https://github.com/mikaelnousiainen/RS41ng/issues/50>, to be able to integrate some of this code into other projects (e.g. the RS41ng repository), there needs to be some license included in your repository.

If you're happy with the GPL v2 license, then just including the https://raw.githubusercontent.com/mikaelnousiainen/RS41ng/main/LICENSE.md file in your repository would be sufficient.

**Comment by darksidelemm** [comment]
The LICENSE file in the repository is sufficient. 
You do sometimes see people put a short version of the GPL statement at the top of their source files, but it's not really necessary in this case.

**Comment by wb9coy** [comment]
Hi Mark I added the LICENSE file.
________________________________

**Comment by darksidelemm** [comment]
Thanks! Much appreciated...
